<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }

    public function _test()
    {
        $released_list = collect([
            ['MARK ANTHONY', '', 'DELA TORRE', 'JUNE 21, 2019', 'JUNE 25, 2019'],
            ['JOEL', 'CUBEL', 'POBLETE', 'JUNE 13, 2019', 'JUNE 17, 2019'],
            ['JOHN ROLAND', 'CUBEL', 'POBLETE', 'JUNE 13, 2019', 'JUNE 17, 2020'],
            ['FREDERICK', 'CUBEL', 'POBLETE', 'JUNE 13, 2019', 'JUNE 17, 2021'],
            ['JAYBERT', 'CUBEL', 'POBLETE', 'JUNE 13, 2019', 'JUNE 17, 2022'],
            ['JERRY', 'SANCHEZ', 'ANDO', 'JUNE 10, 2019', 'JULY 9, 2019'],
            ['LESTER JOHN', 'CAROLINO', 'BACOY', 'JUNE 24, 2019', 'JULY 9, 2019'],
            ['MANUEL', 'ROBIO', 'CARDONA', 'JULY 12, 2019', 'JULY 15, 2019'],
            ['EDUARDO', 'MAKINAY', 'CASAÑAS', 'JUNE 9, 2019', 'JULY 9, 2019'],
            ['ANDY', '', 'DELOS REYES', 'JULY 8, 2019', 'JULY 9, 2019'],
            ['ALLAN', 'FERRY', 'DIAZ', 'JUNE 9, 2019', 'JULY 9, 2019'],
            ['NILO', 'MEDALLA', 'ESPIJON', 'MAY 12, 2019', 'JULY 9, 2019'],
            ['MARLON', 'MARQUEZ', 'GUILLERMO', 'MAY 1, 2019', 'JULY 9, 2019'],
            ['ROCHIE', 'ESTRADA', 'HEBRON', 'MAY 18, 2019', 'JULY 9, 2019'],
            ['MARVIN', 'B', 'LIGION', 'JULY 19, 2019', 'JULY 23, 2019'],
            ['MARCOS', 'ESMERIA', 'MAGPALE', 'MAY 1, 2019', 'JULY 9, 2019'],
            ['EDWIN', 'SABITE', 'MEDINA', 'MAY 1, 2019', 'JULY 9, 2019'],
            ['JESSIE', 'DETABLAN', 'PAGUIBITAN', 'JUNE 21, 2019', 'JULY 9, 2019'],
            ['DARLEEN MELODY', '', 'PEBENEL', 'JULY 19, 2019', 'JULY 19, 2019'],
            ['ROMEO', '', 'RECTO', 'JULY 23, 2019', 'JULY 24, 2019'],
            ['ALLAN', 'ALMOGUERA', 'ROBLES', 'JANUARY 15, 2019', 'JULY 7, 2019'],
            ['ROGER', 'OCAMPO', 'SARMIENTO', 'MAY 24, 2019', 'JULY 9, 2019'],
            ['ALBERT', 'MASANGCAY', 'SUAREZ', 'MAY 30, 2019', 'JULY 9, 2019'],
            ['MICHAEL', 'S', 'TOLENTINO', 'JULY 22, 2019', 'JULY 31, 2019'],
            ['JEFFREY', 'DALIN', 'VERNEZA', 'JULY 2, 2019', 'JULY 5, 2019'],
            ['MANUEL', 'AVINCULA', 'LAYDEROS', 'AUGUST 19, 2019', 'AUGUST 27, 2019'],
            ['MICHAEL', 'VIDAL', 'REYES', 'JULY 25, 2019', 'AUGUST 6, 2019'],
            ['RONIE', 'URISANTOS', 'SARMIENTO', 'JULY 22, 2019', 'AUGUST 2, 2019'],
            ['MANUEL MELI', 'CARREON', 'SEAN', 'AUGUST 2, 2019', 'AUGUST 6, 2019'],
            ['STEWART III', 'NELSON', 'THOMAS', 'AUGUST 2, 2019', 'AUGUST 6, 2019'],
            ['RIGEL', 'ALVELS', 'VIDAL', 'JULY 25, 2019', 'AUGUST 6, 2019'],
            ['BERNARDINO', 'AZUCENA', 'ACYATAN', 'AUGUST 7, 2019', 'SEPTEMBER 19, 2019'],
            ['ARIEL', 'HAIN', 'BATAS', 'SEPTEMBER 15, 2019', 'SEPTEMBER 18, 2019'],
            ['WILLIAM', 'BAYSON', 'CAPANAYAN', 'AUGUST 1, 2019', 'SEPTEMBER 19, 2019'],
            ['JADE', 'SAN PEDRO', 'DELFIN', 'AUGUST 8, 2019', 'SEPTEMBER 19, 2019'],
            ['JUAN', '', 'ESPITITU', 'JULY 20, 2019', 'SEPTEMBER 3, 2019'],
            ['RICHARD', 'HENON', 'GIMAO', 'MAY 17, 109', 'SEPTEMBER 3, 2019'],
            ['LAURO', 'URISANTOS', 'INSORIO', 'AUGUST 7, 2019', 'SEPTEMBER 19, 2019'],
            ['RAMIEL', 'CORTEZ', 'LLANDO', 'JUNE 27, 2019', 'SEPTEMBER 3, 2019'],
            ['JAY AR', 'ALWINA', 'LUDANG', 'AUGUST 8, 2019', 'SEPTEMBER 19, 2019'],
            ['RICHARD', 'B', 'MAGINAO', 'JULY 11, 2019', 'SEPTEMBER 3, 2019'],
            ['STEPHANE', 'TAKUYAM', 'MALAYON', 'AUGUST 12, 2019', 'SEPTEMBER 26, 2019'],
            ['PAUL ANDREW', 'S', 'OSMA', 'AUGUST 8, 2020', 'SEPTEMBER 19, 2019'],
            ['MARK', 'GASILO', 'PALMA', 'SEPTEMBER 3, 2019', 'SEPTEMBER 4, 2019'],
            ['ANGELITO', 'REYES', 'PURIFICATION', 'SEPTEMBER 14, 2019', 'SEPTEMBER 17, 2019'],
            ['ROSILITO', 'BARRIGA', 'ABILA', 'SEPTEMBER 23, 2019', 'OCTOBER 27, 2019'],
            ['VIBENCIO JR', 'PARAYAN', 'ALICBUSAN', 'SEPTEMBER 23, 2019', 'OCTOBER 27, 2019'],
            ['ARMANDO', 'BATITIS', 'ALTAGTAG', 'SEPTEMBER 23, 2019', 'OCTOBER 27, 2019'],
            ['CHRISTIAN', 'ESPAÑOLA', 'AMAR', 'OCTOBER 27, 2019', 'OCTOBER 29, 2019'],
            ['LEO', 'AVENTEJO', 'CORTIZO', 'OCTOBER 27, 2019', 'OCTOBER 29, 2019'],
            ['AGAPITO', 'PACIA', 'DE SALIT', 'AUGUST 30, 2019', 'OCTOBER 27, 2019'],
            ['JINIE', 'EMBIADO', 'ERMEHE', 'OCTOBER 27, 2019', 'OCTOBER 29, 2019'],
            ['ARMANDO', 'OSENIA', 'GUINTO', 'AUGUST 8, 2019', 'OCTOBER 27, 2019'],
            ['EDUARDO', 'OSENIA', 'GUINTO', 'AUGUST 8, 2019', 'OCTOBER 27, 2019'],
            ['RENALDO', 'REVERA', 'MAÑABO', 'JULY 13, 2019', 'OCTOBER 27, 2019'],
            ['ERNILITO', 'LANCETA', 'MARALLA', 'SEPTEMBER 3, 2019', 'OCTOBER 27, 2019'],
            ['LEONCIO', 'HUGASAN', 'OPUS', 'OCTOBER 27, 2019', 'OCTOBER 29, 2019'],
            ['ROLDAN', 'PAGANAN', 'PAÑITARES', 'OCTOBER 27, 2019', 'OCTOBER 29, 2019'],
            ['GODOFREDO', 'MATAN', 'PURIFICATION', 'AUGUST 1, 2019', 'OCTOBER 11, 2019'],
            ['BRYAN', 'KAURELIO', 'RAMOS', 'OCTOBER 18, 2019', 'OCTOBER 21, 2019'],
            ['RAINIEL', 'CALUARIO', 'REÑOLA', 'OCTOBER 27, 2019', 'OCTOBER 29, 2019'],
            ['MICHAEL', 'GONZALES', 'REYES', 'SEPTEMBER 23, 2019', 'OCTOBER 27, 2019'],
            ['FERNAN', 'REYES', 'SIÑO', 'SEPTEMBER 10, 2019', 'OCTOBER 27, 2019'],
            ['DENIS', 'BAUTISTA', 'SITCHON', 'SEPTEMBER 23, 2019', 'OCTOBER 27, 2019'],
            ['CRISTOPER', 'ACMENORAL', 'TEÑIDO', 'SEPTEMBER 16, 2019', 'OCTOBER 27, 2019'],
            ['RONALD', 'MALABANAN', 'ZAMORA', 'JULY 13, 2019', 'OCTOBER 27, 2019'],
            ['RICARDO', 'REYES', 'ZAMORA', 'SEPTEMBER 10, 2019', 'OCTOBER 27, 2019'],
            ['HANZ', 'PADILLA', 'VERGARA', 'OCTOBER 29, 2019', 'NOVEMBER 5, 2019'],
            ['VIDAL', 'LARA', 'BAUTISTA', 'OCTOBER 18, 2019', 'DECEMBER 16, 2019'],
            ['RENAN', 'BERMESO', 'BERNARDINO', 'DECEMBER 9, 2019', 'DECEMBER 16, 2019'],
            ['RONIE', 'CORBO', 'LEGASPI', 'OCTOBER 18, 2019', 'DECEMBER 16, 2019'],
            ['JOSE', 'NODIE', 'LOBO', 'OCTOBER 7, 2019', 'DECEMBER 16, 2019'],
            ['EMILITO', 'MENDOZA', 'MANUEL', 'DECEMBER 13, 2019', 'DECEMBER 16, 2019'],
            ['JULIUS', 'PANCIBANIE', 'MARANTAN', 'OCTOBER 18, 2019', 'DECEMBER 16, 2019'],
            ['JAYBERT', 'CUBEL', 'POBLETE', 'NOVEMBER 21, 2019', 'DECEMBER 16, 2019'],
            ['NORBERTO', 'ATIENZA', 'PURIFICACION', 'NOVEMBER 27, 2019', 'DECEMBER 2, 2019'],
            ['RONNIE', 'BABILA', 'REYES', 'SEPTEMBER 25, 2018', 'DECEMBER 16, 2019'],
            ['MARK ANTHONY', 'EVANGELISTA', 'REYES', 'NOVEMBER 30, 2019', 'DECEMBER 5, 2019'],
            ['JOHN CHRISTOPEHER', 'ANGELES', 'SAMSON', 'DECEMBER 9, 2020', 'DECEMBER 12, 2019'],
            ['RYAN', 'BALMOS', 'SIMON', 'DECEMBER 9, 2019', 'DECEMBER 12, 2019'],
            ['ALBERT', 'DUKE', 'URISANTOS', 'NOVEMBER 21, 2019', 'DECEMBER 16, 2019'],
            ['CERILLO', 'PEROSO', 'VILLANUEVA', 'OCTOBER 18, 2019', 'DECEMBER 16, 2019'],
        ]);

        $detained_list = collect([
            ['JERRY', 'SANCHEZ', 'ANDO', 'JUNE 10, 2019', 'DETAINED',],
            ['LESTER JOHN', 'CAROLINO', 'BACOY', 'JUNE 24, 2019', 'DETAINED',],
            ['EDUARDO', 'MAKINAY', 'CASAÑAS', 'JUNE 9, 2019', 'DETAINED',],
            ['ALLAN', 'FERRY', 'DIAZ', 'JUNE 9, 2019', 'DETAINED',],
            ['NILO', 'MEDALLA', 'ESPIJON', 'MAY 12, 2019', 'DETAINED',],
            ['RICHARD', 'HENON', 'GIMAO', 'MAY 17, 109', 'DETAINED',],
            ['MARLON', 'MARQUEZ', 'GUILLERMO', 'MAY 1, 2019', 'DETAINED',],
            ['ROCHIE', 'ESTRADA', 'HEBRON', 'MAY 18, 2019', 'DETAINED',],
            ['RAMIEL', 'CORTEZ', 'LLANDO', 'JUNE 27, 2019', 'DETAINED',],
            ['MARCOS', 'ESMERIA', 'MAGPALE', 'MAY 1, 2019', 'DETAINED',],
            ['EDWIN', 'SABITE', 'MEDINA', 'MAY 1, 2019', 'DETAINED',],
            ['JESSIE', 'DETABLAN', 'PAGUIBITAN', 'JUNE 21, 2019', 'DETAINED',],
            ['RONNIE', 'BABILA', 'REYES', 'SEPTEMBER 25, 2018', 'DETAINED',],
            ['ARNEL', 'LARIT', 'RICO', 'MAY 12, 2019', 'DETAINED',],
            ['ALLAN', 'ALMOGUERA', 'ROBLES', 'JANUARY 15, 2019', 'DETAINED',],
            ['ROGER', 'OCAMPO', 'SARMIENTO', 'MAY 24, 2019', 'DETAINED',],
            ['ALBERT', 'MASANGCAY', 'SUAREZ', 'MAY 30, 2019', 'DETAINED',],
            ['JUAN', '0', 'ESPITITU', 'JULY 20, 2019', 'DETAINED',],
            ['RICHARD', 'B', 'MAGINAO', 'JULY 11, 2019', 'DETAINED',],
            ['RENALDO', 'REVERA', 'MAÑABO', 'JULY 13, 2019', 'DETAINED',],
            ['MICHAEL', 'VIDAL', 'REYES', 'JULY 25, 2019', 'DETAINED',],
            ['RONIE', 'URISANTOS', 'SARMIENTO', 'JULY 22, 2019', 'DETAINED',],
            ['RIGEL', 'ALVELS', 'VIDAL', 'JULY 25, 2019', 'DETAINED',],
            ['RONALD', 'MALABANAN', 'ZAMORA', 'JULY 13, 2019', 'DETAINED',],
            ['BERNARDINO', 'AZUCENA', 'ACYATAN', 'AUGUST 7, 2019', 'DETAINED',],
            ['WILLIAM', 'BAYSON', 'CAPANAYAN', 'AUGUST 1, 2019', 'DETAINED',],
            ['AGAPITO', 'PACIA', 'DE SALIT', 'AUGUST 30, 2019', 'DETAINED',],
            ['JADE', 'SAN PEDRO', 'DELFIN', 'AUGUST 8, 2019', 'DETAINED',],
            ['ARMANDO', 'OSENIA', 'GUINTO', 'AUGUST 8, 2019', 'DETAINED',],
            ['EDUARDO', 'OSENIA', 'GUINTO', 'AUGUST 8, 2019', 'DETAINED',],
            ['LAURO', 'URISANTOS', 'INSORIO', 'AUGUST 7, 2019', 'DETAINED',],
            ['JAY AR', 'ALWINA', 'LUDANG', 'AUGUST 8, 2019', 'DETAINED',],
            ['STEPHANE', 'TAKUYAM', 'MALAYON', 'AUGUST 12, 2019', 'DETAINED',],
            ['PAUL ANDREW', 'S', 'OSMA', 'AUGUST 8, 2020', 'DETAINED',],
            ['GODOFREDO', 'MATAN', 'PURIFICATION', 'AUGUST 1, 2019', 'DETAINED',],
            ['ROSILITO', 'BARRIGA', 'ABILA', 'SEPTEMBER 23, 2019', 'DETAINED',],
            ['VIBENCIO JR', 'PARAYAN', 'ALICBUSAN', 'SEPTEMBER 23, 2019', 'DETAINED',],
            ['ARMANDO', 'BATITIS', 'ALTAGTAG', 'SEPTEMBER 23, 2019', 'DETAINED',],
            ['ERNILITO', 'LANCETA', 'MARALLA', 'SEPTEMBER 3, 2019', 'DETAINED',],
            ['MICHAEL', 'GONZALES', 'REYES', 'SEPTEMBER 23, 2019', 'DETAINED',],
            ['FERNAN', 'REYES', 'SIÑO', 'SEPTEMBER 10, 2019', 'DETAINED',],
            ['DENIS', 'BAUTISTA', 'SITCHON', 'SEPTEMBER 23, 2019', 'DETAINED',],
            ['CRISTOPER', 'ACMENORAL', 'TEÑIDO', 'SEPTEMBER 16, 2019', 'DETAINED',],
            ['RICARDO', 'REYES', 'ZAMORA', 'SEPTEMBER 10, 2019', 'DETAINED',],
            ['VIDAL', 'LARA', 'BAUTISTA', 'OCTOBER 18, 2019', 'DETAINED',],
            ['RONIE', 'CORBO', 'LEGASPI', 'OCTOBER 18, 2019', 'DETAINED',],
            ['JOSE', 'NODIE', 'LOBO', 'OCTOBER 7, 2019', 'DETAINED',],
            ['RICHARD', 'SANTIAGO', 'MAALA', 'OCTOBER 10, 2019', 'DETAINED',],
            ['JULIUS', 'PANCIBANIE', 'MARANTAN', 'OCTOBER 18, 2019', 'DETAINED',],
            ['JONATHAN', 'MAPAGDAUTAN', 'METRE', 'OCTOBER 26, 2019', 'DETAINED',],
            ['HANZ', 'PADILLA', 'VERGARA', 'OCTOBER 29, 2019', 'DETAINED',],
            ['CERILLO', 'PEROSO', 'VILLANUEVA', 'OCTOBER 18, 2019', 'DETAINED',],
            ['JOHN MICHAEL', 'ZAMORA', 'BARTOLAZO', 'NOVEMBER 26, 2019', 'DETAINED',],
            ['NEIL', 'DAPROSO', 'CABLAO', 'NOVEMBER 7, 2019', 'DETAINED',],
            ['RIENZI', 'SARMIENTO', 'DABU', 'NOVEMBER 29, 2019', 'DETAINED',],
            ['CHRISTIAN', 'ESPIRITU', 'DELOS SANTOS', 'NOVEMBER 26, 2019', 'DETAINED',],
            ['JENNA', 'YANILLA', 'LIBID', 'NOVEMBER 7, 2019', 'DETAINED',],
            ['JENNIFER', 'MENDOZA', 'MANUEL', 'NOVEMBER 7, 2019', 'DETAINED',],
            ['FELISCIANO', 'MARVILLA', 'NAVAL', 'NOVEMBER 29, 2019', 'DETAINED',],
            ['ROY', 'VILLAFLORES', 'PAQUITA', 'NOVEMBER 26, 2019', 'DETAINED',],
            ['JAYBERT', 'CUBEL', 'POBLETE', 'NOVEMBER 21, 2019', 'DETAINED',],
            ['NORBERTO', 'ATIENZA', 'PURIFICACION', 'NOVEMBER 27, 2019', 'DETAINED',],
            ['MARK ANTHONY', 'EVANGELISTA', 'REYES', 'NOVEMBER 30, 2019', 'DETAINED',],
            ['ALBERT', 'DUKE', 'URISANTOS', 'NOVEMBER 21, 2019', 'DETAINED',],
            ['RONNEL', 'RUIZ', 'ALEROSO', 'DECEMBER 12, 2019', 'DETAINED',],
            ['ALDRIN', 'LONTOC', 'ANTIPALO', 'DECEMBER 1, 2019', 'DETAINED',],
            ['JOMAR', 'DELA PEÑA', 'ASILO', 'DECEMBER 25, 2019', 'DETAINED',],
            ['RONALD', 'TRINIDAD', 'CARAVANA', 'DECEMBER 12, 2019', 'DETAINED',],
            ['ARIEL', 'DUANA', 'DE ASIS', 'DECEMBER 12, 2019', 'DETAINED',],
            ['DANILO', 'RAMIREZ', 'GALANDEZ', 'DECEMBER 12, 2019', 'DETAINED',],
        ]);


        $released_list = $released_list->map(function($item, $key) {
            $item = [
                'first_name' => $item[0],
                'middle_name' => $item[1] ? : null,
                'last_name' => $item[2],
                'detained_date' => Carbon::createFromFormat('F j, Y', mb_strtolower(ucwords($item[3])))->format('m/d/Y'),
                'released_date' => Carbon::createFromFormat('F j, Y', mb_strtolower(ucwords($item[4])))->format('m/d/Y'),
            ];

            return $item;
        });

        $not_in_released = $detained_list->map(function($item, $key) use ($released_list) {

            $item = [
                'first_name' => $item[0],
                'middle_name' => $item[1] ? : null,
                'last_name' => $item[2],
                'detained_date' => Carbon::createFromFormat('F j, Y', mb_strtolower(ucwords($item[3])))->format('m/d/Y'),
                // 'released_date' => Carbon::createFromFormat('F j, Y', mb_strtolower(ucwords($item[4])))->format('m/d/Y'),
            ];

            if (($released_list->where('first_name', $item['first_name'])->count() > 0 && $released_list->where('last_name', $item['last_name'])->count() > 0)) {
                return false;
            } else {
                return $item;
            }

        })->filter();

        foreach ($released_list as $released) {
            echo "<pre>";
            var_export($released);
            echo ',';
        }

        dd('___________');

        // dd($detained_list);
        dd($released_list);
        // dd($not_in_released);
    }

    public function test()
    {
        $released_list = [
            [
              'first_name' => 'MARK ANTHONY',
              'middle_name' => NULL,
              'last_name' => 'DELA TORRE',
              'detained_date' => '06/21/2019',
              'released_date' => '06/25/2019',
            ],
            [
              'first_name' => 'JOEL',
              'middle_name' => 'CUBEL',
              'last_name' => 'POBLETE',
              'detained_date' => '06/13/2019',
              'released_date' => '06/17/2019',
            ],
            [
              'first_name' => 'JOHN ROLAND',
              'middle_name' => 'CUBEL',
              'last_name' => 'POBLETE',
              'detained_date' => '06/13/2019',
              'released_date' => '06/17/2020',
            ],
            [
              'first_name' => 'FREDERICK',
              'middle_name' => 'CUBEL',
              'last_name' => 'POBLETE',
              'detained_date' => '06/13/2019',
              'released_date' => '06/17/2021',
            ],
            [
              'first_name' => 'JAYBERT',
              'middle_name' => 'CUBEL',
              'last_name' => 'POBLETE',
              'detained_date' => '06/13/2019',
              'released_date' => '06/17/2022',
            ],
            [
              'first_name' => 'JERRY',
              'middle_name' => 'SANCHEZ',
              'last_name' => 'ANDO',
              'detained_date' => '06/10/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'LESTER JOHN',
              'middle_name' => 'CAROLINO',
              'last_name' => 'BACOY',
              'detained_date' => '06/24/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'MANUEL',
              'middle_name' => 'ROBIO',
              'last_name' => 'CARDONA',
              'detained_date' => '07/12/2019',
              'released_date' => '07/15/2019',
            ],
            [
              'first_name' => 'EDUARDO',
              'middle_name' => 'MAKINAY',
              'last_name' => 'CASAÑAS',
              'detained_date' => '06/09/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'ANDY',
              'middle_name' => NULL,
              'last_name' => 'DELOS REYES',
              'detained_date' => '07/08/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'ALLAN',
              'middle_name' => 'FERRY',
              'last_name' => 'DIAZ',
              'detained_date' => '06/09/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'NILO',
              'middle_name' => 'MEDALLA',
              'last_name' => 'ESPIJON',
              'detained_date' => '05/12/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'MARLON',
              'middle_name' => 'MARQUEZ',
              'last_name' => 'GUILLERMO',
              'detained_date' => '05/01/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'ROCHIE',
              'middle_name' => 'ESTRADA',
              'last_name' => 'HEBRON',
              'detained_date' => '05/18/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'MARVIN',
              'middle_name' => 'B',
              'last_name' => 'LIGION',
              'detained_date' => '07/19/2019',
              'released_date' => '07/23/2019',
            ],
            [
              'first_name' => 'MARCOS',
              'middle_name' => 'ESMERIA',
              'last_name' => 'MAGPALE',
              'detained_date' => '05/01/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'EDWIN',
              'middle_name' => 'SABITE',
              'last_name' => 'MEDINA',
              'detained_date' => '05/01/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'JESSIE',
              'middle_name' => 'DETABLAN',
              'last_name' => 'PAGUIBITAN',
              'detained_date' => '06/21/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'DARLEEN MELODY',
              'middle_name' => NULL,
              'last_name' => 'PEBENEL',
              'detained_date' => '07/19/2019',
              'released_date' => '07/19/2019',
            ],
            [
              'first_name' => 'ROMEO',
              'middle_name' => NULL,
              'last_name' => 'RECTO',
              'detained_date' => '07/23/2019',
              'released_date' => '07/24/2019',
            ],
            [
              'first_name' => 'ALLAN',
              'middle_name' => 'ALMOGUERA',
              'last_name' => 'ROBLES',
              'detained_date' => '01/15/2019',
              'released_date' => '07/07/2019',
            ],
            [
              'first_name' => 'ROGER',
              'middle_name' => 'OCAMPO',
              'last_name' => 'SARMIENTO',
              'detained_date' => '05/24/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'ALBERT',
              'middle_name' => 'MASANGCAY',
              'last_name' => 'SUAREZ',
              'detained_date' => '05/30/2019',
              'released_date' => '07/09/2019',
            ],
            [
              'first_name' => 'MICHAEL',
              'middle_name' => 'S',
              'last_name' => 'TOLENTINO',
              'detained_date' => '07/22/2019',
              'released_date' => '07/31/2019',
            ],
            [
              'first_name' => 'JEFFREY',
              'middle_name' => 'DALIN',
              'last_name' => 'VERNEZA',
              'detained_date' => '07/02/2019',
              'released_date' => '07/05/2019',
            ],
            [
              'first_name' => 'MANUEL',
              'middle_name' => 'AVINCULA',
              'last_name' => 'LAYDEROS',
              'detained_date' => '08/19/2019',
              'released_date' => '08/27/2019',
            ],
            [
              'first_name' => 'MICHAEL',
              'middle_name' => 'VIDAL',
              'last_name' => 'REYES',
              'detained_date' => '07/25/2019',
              'released_date' => '08/06/2019',
            ],
            [
              'first_name' => 'RONIE',
              'middle_name' => 'URISANTOS',
              'last_name' => 'SARMIENTO',
              'detained_date' => '07/22/2019',
              'released_date' => '08/02/2019',
            ],
            [
              'first_name' => 'MANUEL MELI',
              'middle_name' => 'CARREON',
              'last_name' => 'SEAN',
              'detained_date' => '08/02/2019',
              'released_date' => '08/06/2019',
            ],
            [
              'first_name' => 'STEWART III',
              'middle_name' => 'NELSON',
              'last_name' => 'THOMAS',
              'detained_date' => '08/02/2019',
              'released_date' => '08/06/2019',
            ],
            [
              'first_name' => 'RIGEL',
              'middle_name' => 'ALVELS',
              'last_name' => 'VIDAL',
              'detained_date' => '07/25/2019',
              'released_date' => '08/06/2019',
            ],
            [
              'first_name' => 'BERNARDINO',
              'middle_name' => 'AZUCENA',
              'last_name' => 'ACYATAN',
              'detained_date' => '08/07/2019',
              'released_date' => '09/19/2019',
            ],
            [
              'first_name' => 'ARIEL',
              'middle_name' => 'HAIN',
              'last_name' => 'BATAS',
              'detained_date' => '09/15/2019',
              'released_date' => '09/18/2019',
            ],
            [
              'first_name' => 'WILLIAM',
              'middle_name' => 'BAYSON',
              'last_name' => 'CAPANAYAN',
              'detained_date' => '08/01/2019',
              'released_date' => '09/19/2019',
            ],
            [
              'first_name' => 'JADE',
              'middle_name' => 'SAN PEDRO',
              'last_name' => 'DELFIN',
              'detained_date' => '08/08/2019',
              'released_date' => '09/19/2019',
            ],
            [
              'first_name' => 'JUAN',
              'middle_name' => NULL,
              'last_name' => 'ESPITITU',
              'detained_date' => '07/20/2019',
              'released_date' => '09/03/2019',
            ],
            [
              'first_name' => 'RICHARD',
              'middle_name' => 'HENON',
              'last_name' => 'GIMAO',
              'detained_date' => '05/17/0109',
              'released_date' => '09/03/2019',
            ],
            [
              'first_name' => 'LAURO',
              'middle_name' => 'URISANTOS',
              'last_name' => 'INSORIO',
              'detained_date' => '08/07/2019',
              'released_date' => '09/19/2019',
            ],
            [
              'first_name' => 'RAMIEL',
              'middle_name' => 'CORTEZ',
              'last_name' => 'LLANDO',
              'detained_date' => '06/27/2019',
              'released_date' => '09/03/2019',
            ],
            [
              'first_name' => 'JAY AR',
              'middle_name' => 'ALWINA',
              'last_name' => 'LUDANG',
              'detained_date' => '08/08/2019',
              'released_date' => '09/19/2019',
            ],
            [
              'first_name' => 'RICHARD',
              'middle_name' => 'B',
              'last_name' => 'MAGINAO',
              'detained_date' => '07/11/2019',
              'released_date' => '09/03/2019',
            ],
            [
              'first_name' => 'STEPHANE',
              'middle_name' => 'TAKUYAM',
              'last_name' => 'MALAYON',
              'detained_date' => '08/12/2019',
              'released_date' => '09/26/2019',
            ],
            [
              'first_name' => 'PAUL ANDREW',
              'middle_name' => 'S',
              'last_name' => 'OSMA',
              'detained_date' => '08/08/2020',
              'released_date' => '09/19/2019',
            ],
            [
              'first_name' => 'MARK',
              'middle_name' => 'GASILO',
              'last_name' => 'PALMA',
              'detained_date' => '09/03/2019',
              'released_date' => '09/04/2019',
            ],
            [
              'first_name' => 'ANGELITO',
              'middle_name' => 'REYES',
              'last_name' => 'PURIFICATION',
              'detained_date' => '09/14/2019',
              'released_date' => '09/17/2019',
            ],
            [
              'first_name' => 'ROSILITO',
              'middle_name' => 'BARRIGA',
              'last_name' => 'ABILA',
              'detained_date' => '09/23/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'VIBENCIO JR',
              'middle_name' => 'PARAYAN',
              'last_name' => 'ALICBUSAN',
              'detained_date' => '09/23/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'ARMANDO',
              'middle_name' => 'BATITIS',
              'last_name' => 'ALTAGTAG',
              'detained_date' => '09/23/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'CHRISTIAN',
              'middle_name' => 'ESPAÑOLA',
              'last_name' => 'AMAR',
              'detained_date' => '10/27/2019',
              'released_date' => '10/29/2019',
            ],
            [
              'first_name' => 'LEO',
              'middle_name' => 'AVENTEJO',
              'last_name' => 'CORTIZO',
              'detained_date' => '10/27/2019',
              'released_date' => '10/29/2019',
            ],
            [
              'first_name' => 'AGAPITO',
              'middle_name' => 'PACIA',
              'last_name' => 'DE SALIT',
              'detained_date' => '08/30/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'JINIE',
              'middle_name' => 'EMBIADO',
              'last_name' => 'ERMEHE',
              'detained_date' => '10/27/2019',
              'released_date' => '10/29/2019',
            ],
            [
              'first_name' => 'ARMANDO',
              'middle_name' => 'OSENIA',
              'last_name' => 'GUINTO',
              'detained_date' => '08/08/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'EDUARDO',
              'middle_name' => 'OSENIA',
              'last_name' => 'GUINTO',
              'detained_date' => '08/08/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'RENALDO',
              'middle_name' => 'REVERA',
              'last_name' => 'MAÑABO',
              'detained_date' => '07/13/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'ERNILITO',
              'middle_name' => 'LANCETA',
              'last_name' => 'MARALLA',
              'detained_date' => '09/03/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'LEONCIO',
              'middle_name' => 'HUGASAN',
              'last_name' => 'OPUS',
              'detained_date' => '10/27/2019',
              'released_date' => '10/29/2019',
            ],
            [
              'first_name' => 'ROLDAN',
              'middle_name' => 'PAGANAN',
              'last_name' => 'PAÑITARES',
              'detained_date' => '10/27/2019',
              'released_date' => '10/29/2019',
            ],
            [
              'first_name' => 'GODOFREDO',
              'middle_name' => 'MATAN',
              'last_name' => 'PURIFICATION',
              'detained_date' => '08/01/2019',
              'released_date' => '10/11/2019',
            ],
            [
              'first_name' => 'BRYAN',
              'middle_name' => 'KAURELIO',
              'last_name' => 'RAMOS',
              'detained_date' => '10/18/2019',
              'released_date' => '10/21/2019',
            ],
            [
              'first_name' => 'RAINIEL',
              'middle_name' => 'CALUARIO',
              'last_name' => 'REÑOLA',
              'detained_date' => '10/27/2019',
              'released_date' => '10/29/2019',
            ],
            [
              'first_name' => 'MICHAEL',
              'middle_name' => 'GONZALES',
              'last_name' => 'REYES',
              'detained_date' => '09/23/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'FERNAN',
              'middle_name' => 'REYES',
              'last_name' => 'SIÑO',
              'detained_date' => '09/10/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'DENIS',
              'middle_name' => 'BAUTISTA',
              'last_name' => 'SITCHON',
              'detained_date' => '09/23/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'CRISTOPER',
              'middle_name' => 'ACMENORAL',
              'last_name' => 'TEÑIDO',
              'detained_date' => '09/16/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'RONALD',
              'middle_name' => 'MALABANAN',
              'last_name' => 'ZAMORA',
              'detained_date' => '07/13/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'RICARDO',
              'middle_name' => 'REYES',
              'last_name' => 'ZAMORA',
              'detained_date' => '09/10/2019',
              'released_date' => '10/27/2019',
            ],
            [
              'first_name' => 'HANZ',
              'middle_name' => 'PADILLA',
              'last_name' => 'VERGARA',
              'detained_date' => '10/29/2019',
              'released_date' => '11/05/2019',
            ],
            [
              'first_name' => 'VIDAL',
              'middle_name' => 'LARA',
              'last_name' => 'BAUTISTA',
              'detained_date' => '10/18/2019',
              'released_date' => '12/16/2019',
            ],
            [
              'first_name' => 'RENAN',
              'middle_name' => 'BERMESO',
              'last_name' => 'BERNARDINO',
              'detained_date' => '12/09/2019',
              'released_date' => '12/16/2019',
            ],
            [
              'first_name' => 'RONIE',
              'middle_name' => 'CORBO',
              'last_name' => 'LEGASPI',
              'detained_date' => '10/18/2019',
              'released_date' => '12/16/2019',
            ],
            [
              'first_name' => 'JOSE',
              'middle_name' => 'NODIE',
              'last_name' => 'LOBO',
              'detained_date' => '10/07/2019',
              'released_date' => '12/16/2019',
            ],
            [
              'first_name' => 'EMILITO',
              'middle_name' => 'MENDOZA',
              'last_name' => 'MANUEL',
              'detained_date' => '12/13/2019',
              'released_date' => '12/16/2019',
            ],
            [
              'first_name' => 'JULIUS',
              'middle_name' => 'PANCIBANIE',
              'last_name' => 'MARANTAN',
              'detained_date' => '10/18/2019',
              'released_date' => '12/16/2019',
            ],
            [
              'first_name' => 'JAYBERT',
              'middle_name' => 'CUBEL',
              'last_name' => 'POBLETE',
              'detained_date' => '11/21/2019',
              'released_date' => '12/16/2019',
            ],
            [
              'first_name' => 'NORBERTO',
              'middle_name' => 'ATIENZA',
              'last_name' => 'PURIFICACION',
              'detained_date' => '11/27/2019',
              'released_date' => '12/02/2019',
            ],
            [
              'first_name' => 'RONNIE',
              'middle_name' => 'BABILA',
              'last_name' => 'REYES',
              'detained_date' => '09/25/2018',
              'released_date' => '12/16/2019',
            ],
            [
              'first_name' => 'MARK ANTHONY',
              'middle_name' => 'EVANGELISTA',
              'last_name' => 'REYES',
              'detained_date' => '11/30/2019',
              'released_date' => '12/05/2019',
            ],
            [
              'first_name' => 'JOHN CHRISTOPEHER',
              'middle_name' => 'ANGELES',
              'last_name' => 'SAMSON',
              'detained_date' => '12/09/2020',
              'released_date' => '12/12/2019',
            ],
            [
              'first_name' => 'RYAN',
              'middle_name' => 'BALMOS',
              'last_name' => 'SIMON',
              'detained_date' => '12/09/2019',
              'released_date' => '12/12/2019',
            ],
            [
              'first_name' => 'ALBERT',
              'middle_name' => 'DUKE',
              'last_name' => 'URISANTOS',
              'detained_date' => '11/21/2019',
              'released_date' => '12/16/2019',
            ],
            [
              'first_name' => 'CERILLO',
              'middle_name' => 'PEROSO',
              'last_name' => 'VILLANUEVA',
              'detained_date' => '10/18/2019',
              'released_date' => '12/16/2019',
            ],
        ];

        dd($released_list);
    }
}
